require("plenary.async").tests.add_to_env()
local test_util = require("tests.test_util")

a.describe("regression tests", function()
  after_each(function()
    test_util.reset_editor()
  end)
  -- see https://github.com/stevearc/oil.nvim/issues/25
  a.it("can edit dirs that will be renamed to an existing buffer", function()
    vim.cmd.edit({ args = { "README.md" } })
    vim.cmd.vsplit()
    vim.cmd.edit({ args = { "%:p:h" } })
    assert.equals("oil", vim.bo.filetype)
    vim.cmd.wincmd({ args = { "p" } })
    assert.equals("markdown", vim.bo.filetype)
    vim.cmd.edit({ args = { "%:p:h" } })
    a.util.sleep(10)
    assert.equals("oil", vim.bo.filetype)
  end)
end)
