name: Feature Request
description: Suggest a feature
title: 'feat: '
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label:
            I have searched [existing
            issues](https://github.com/barrettruth/oil.nvim/issues)
          required: true

  - type: textarea
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
